#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           wristServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           intakeMotor,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           clawMotor,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                - Clawbot Single Joystick Control -                                 *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left to drive the robot. Use notes below     *|
|*  to reconfigure which joystick is used. The joystick buttons are used to raise and lower the arm.	*|
|*  The joystick buttons are used to open and close the claw.																					*|
|*																																																		*|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)	Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)	Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*		3)	Button 5U and 5L are on the front left side of the joystick.																*|
|*		3)	Button 6U and 6L are on the front right side of the joystick.																*|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]        [Name]          [Type]                               [Description]            *|
|*    Motor - Port 2   rightMotor    VEX 393 Motor                         Right drive motor          *|
|*    Motor - Port 6   clawMotor     VEX 393 Motor w/ Motor Controler 29   Claw motor                 *|
|*    Motor - Port 7   armMotor      VEX 393 Motor w/ Motor Controler 29   Arm motor                  *|
|*    Motor - Port 10  leftMotor     VEX 393 Motor                         Left drive motor           *|
\*----------------------------------------------------------------------------------------------------*/

//const int c = 15.04;

/*
int rev(d)
{
	int r = d/c;
	int eCount = r * 360;
	return eCount;
}

void shake_bot()
{

}

void forward(eCount)
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	while(SensorValue[rightEncoder] < eCount && SensorValue[leftEncoder] < eCount)
	{
		motor[leftMotor] = 63;
		motor[rightMotor] = 63;
	}
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}
*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{

//++++++++++++++++++++++++++++++++++++++++++| AUTONOMOUS |++++++++++++++++++++++++++++++++++++++++++++

/*
 eCount = rev(30);
 forward(eCount);
*/

//++++++++++++++++++++++++++++++++++++++++| MANUAL CONTROL |++++++++++++++++++++++++++++++++++++++++++

	while(1 == 1)
	{
	// Set Intake motors to zero
		if(vexRT[Btn6U] == 1)
		{
			motor[intakeMotor] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[intakeMotor] = -127;
		}
		else
		{
			motor[intakeMotor] = 0;
		}

	// Wheels
		//motor[leftMotor]  = (vexRT[Ch
		motor[leftMotor]  = (vexRT[Ch4] + vexRT[Ch3])/2;  // (y + x)/2
		motor[rightMotor] = (vexRT[Ch4] - vexRT[Ch3])/2;  // (y - x)/2

	// Arm
		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[armMotor] = 127;    	//...raise the arm.
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[armMotor] = -127;   	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[armMotor] = 0;      	//...stop the arm.
		}

	// Claw
		// Open
		if(vexRT[Btn8U] == 1)
		{
			motor[clawMotor] = 63;
		}
		// CLose
		else if(vexRT[Btn8D] == 1)
		{
			motor[clawMotor] = -63;
		}
		else
		{
			motor[clawMotor] = 0;
		}

	// Wrist
		if(vexRT[Btn8L] == 1)
		{
			motor[wristServo] = 60;
		}
		else if(vexRT[Btn8R] == 1)
		{
			motor[wristServo] = -60;
		}
		else
		{
			motor[wristServo] = 0;
		}
	// Shake Motion
		/*if(vexRT[Btn7D] == 1)
		{
			//shake_bot();
		}
		else
		{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}*/
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
